# Generated by Django 2.0.6 on 2018-09-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('delivery_date', models.DateField(blank=True)),
                ('product_id', models.TextField()),
                ('payment_option', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('order_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='產品列表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名稱', models.CharField(max_length=100, unique=True)),
                ('描述', models.TextField(blank=True)),
                ('圖片', models.ImageField(blank=True, upload_to='category')),
                ('價格', models.DecimalField(decimal_places=4, max_digits=10)),
                ('庫存', models.IntegerField(default=0)),
                ('已上架', models.BooleanField(default=True)),
                ('建立時間', models.DateTimeField(auto_now_add=True)),
                ('修改時間', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '產品列表',
                'db_table': '產品列表',
                'ordering': ('-建立時間',),
            },
        ),
    ]
